- hosts: webserver
  vars :
      - port: 8000
      - dest: /test-task
      - image_name: test-task
  tasks:
    - name: Install git
      apt:
        name: git
        state: present
    
    - name : Clone Project
      git:
        repo: "https://github.com/soksanchhom/test-task.git"
        version: "master"
        dest: "{{dest}}"

    - name: Build the image
      command: docker build -t {{image_name}} {{dest}}

    - name: Running the container
      command: docker run -p {{port}}:80 -d --name {{image_name}}-{{port}} {{image_name}}

  roles:
    - geerlingguy.docker
  